import { Movie } from './classes/movie';

export const MOVIES: Movie[] = [
    {
      "title":"The Dark Knight",
      "year":2008,
      "imdb":"tt0468569",
      "trailer":"https://www.youtube.com/watch?v=EXeTwQWrcwY",
      "reviewClip":"https://www.youtube.com/watch?v=EXeTwQWrcwY",
      "reviewSummary":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dignissim molestie nulla at congue. Cras porttitor tincidunt leo quis sagittis. Duis et dignissim ipsum, a dignissim turpis. Suspendisse dictum justo in dolor blandit hendrerit. Nulla arcu urna, scelerisque a justo et, pretium lobortis arcu. Vestibulum efficitur id risus quis malesuada. Aenean lacinia consectetur massa a ultrices. In orci leo, vehicula non mauris nec, vulputate accumsan magna. Duis at feugiat nibh, vitae eleifend ante,",
      "reviewScore":9,
      "createdAt": new Date(),
      "bestWeek": false,
      "bestMonth": false
    },
    {
      "title":"The Avengers",
      "year":2012,
      "imdb":"tt0848228",
      "trailer":"https://www.youtube.com/watch?v=eOrNdBpGMv8",
      "reviewClip":"https://www.youtube.com/watch?v=eOrNdBpGMv8",
      "reviewSummary":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dignissim molestie nulla at congue. Cras porttitor tincidunt leo quis sagittis. Duis et dignissim ipsum, a dignissim turpis. Suspendisse dictum justo in dolor blandit hendrerit. Nulla arcu urna, scelerisque a justo et, pretium lobortis arcu. Vestibulum efficitur id risus quis malesuada. Aenean lacinia consectetur massa a ultrices. In orci leo, vehicula non mauris nec, vulputate accumsan magna. Duis at feugiat nibh, vitae eleifend ante,",
      "reviewScore":9.5,
      "createdAt": new Date(),
      "bestWeek": false,
      "bestMonth": false
    },
    {
      "title":"Batman v Superman: Dawn of Justice",
      "year":2016,
      "imdb":"tt2975590",
      "trailer":"https://www.youtube.com/watch?v=0WWzgGyAH6Y",
      "reviewClip":"https://www.youtube.com/watch?v=0WWzgGyAH6Y",
      "reviewSummary":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dignissim molestie nulla at congue. Cras porttitor tincidunt leo quis sagittis. Duis et dignissim ipsum, a dignissim turpis. Suspendisse dictum justo in dolor blandit hendrerit. Nulla arcu urna, scelerisque a justo et, pretium lobortis arcu. Vestibulum efficitur id risus quis malesuada. Aenean lacinia consectetur massa a ultrices. In orci leo, vehicula non mauris nec, vulputate accumsan magna. Duis at feugiat nibh, vitae eleifend ante,",
      "reviewScore":7,
      "createdAt": new Date(),
      "bestWeek": false,
      "bestMonth": false
    },
    {
      "title":"Lee Daniels' The Butler",
      "year":2013,
      "imdb":"tt1327773",
      "trailer":"https://www.youtube.com/watch?v=DUA7rr0bOcc",
      "reviewClip":"https://www.youtube.com/watch?v=DUA7rr0bOcc",
      "reviewSummary":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dignissim molestie nulla at congue. Cras porttitor tincidunt leo quis sagittis. Duis et dignissim ipsum, a dignissim turpis. Suspendisse dictum justo in dolor blandit hendrerit. Nulla arcu urna, scelerisque a justo et, pretium lobortis arcu. Vestibulum efficitur id risus quis malesuada. Aenean lacinia consectetur massa a ultrices. In orci leo, vehicula non mauris nec, vulputate accumsan magna. Duis at feugiat nibh, vitae eleifend ante,",
      "reviewScore":8.5,
      "createdAt": new Date(),
      "bestWeek": false,
      "bestMonth": false
    },
    {
      "title":"Get Out",
      "year":2017,
      "imdb":"tt5052448",
      "trailer":"https://www.youtube.com/watch?v=xM1YpntE840",
      "reviewClip":"https://www.youtube.com/watch?v=xM1YpntE840",
      "reviewSummary":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dignissim molestie nulla at congue. Cras porttitor tincidunt leo quis sagittis. Duis et dignissim ipsum, a dignissim turpis. Suspendisse dictum justo in dolor blandit hendrerit. Nulla arcu urna, scelerisque a justo et, pretium lobortis arcu. Vestibulum efficitur id risus quis malesuada. Aenean lacinia consectetur massa a ultrices. In orci leo, vehicula non mauris nec, vulputate accumsan magna. Duis at feugiat nibh, vitae eleifend ante,",
      "reviewScore":9.5,
      "createdAt": new Date(),
      "bestWeek": false,
      "bestMonth": false
    },
    {
      "title":"Taken",
      "year":2008,
      "imdb":"tt0848228",
      "trailer":"https://www.youtube.com/watch?v=uPJVJBm9TPA",
      "reviewClip":"https://www.youtube.com/watch?v=uPJVJBm9TPA",
      "reviewSummary":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dignissim molestie nulla at congue. Cras porttitor tincidunt leo quis sagittis. Duis et dignissim ipsum, a dignissim turpis. Suspendisse dictum justo in dolor blandit hendrerit. Nulla arcu urna, scelerisque a justo et, pretium lobortis arcu. Vestibulum efficitur id risus quis malesuada. Aenean lacinia consectetur massa a ultrices. In orci leo, vehicula non mauris nec, vulputate accumsan magna. Duis at feugiat nibh, vitae eleifend ante,",
      "reviewScore":9,
      "createdAt": new Date(),
      "bestWeek": false,
      "bestMonth": false
    },
    {
      "title":"Hugo",
      "year":2011,
      "imdb":"tt0970179",
      "trailer":"https://www.youtube.com/watch?v=1bA1cL_s6CE",
      "reviewClip":"https://www.youtube.com/watch?v=1bA1cL_s6CE",
      "reviewSummary":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dignissim molestie nulla at congue. Cras porttitor tincidunt leo quis sagittis. Duis et dignissim ipsum, a dignissim turpis. Suspendisse dictum justo in dolor blandit hendrerit. Nulla arcu urna, scelerisque a justo et, pretium lobortis arcu. Vestibulum efficitur id risus quis malesuada. Aenean lacinia consectetur massa a ultrices. In orci leo, vehicula non mauris nec, vulputate accumsan magna. Duis at feugiat nibh, vitae eleifend ante,",
      "reviewScore":6,
      "createdAt": new Date(),
      "bestWeek": false,
      "bestMonth": false
    },
    {
      "title":"The Avengers",
      "year":2008,
      "imdb":"tt0848228",
      "trailer":"https://www.youtube.com/watch?v=eOrNdBpGMv8",
      "reviewClip":"https://www.youtube.com/watch?v=eOrNdBpGMv8",
      "reviewSummary":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dignissim molestie nulla at congue. Cras porttitor tincidunt leo quis sagittis. Duis et dignissim ipsum, a dignissim turpis. Suspendisse dictum justo in dolor blandit hendrerit. Nulla arcu urna, scelerisque a justo et, pretium lobortis arcu. Vestibulum efficitur id risus quis malesuada. Aenean lacinia consectetur massa a ultrices. In orci leo, vehicula non mauris nec, vulputate accumsan magna. Duis at feugiat nibh, vitae eleifend ante,",
      "reviewScore":9.5,
      "createdAt": new Date(),
      "bestWeek": false,
      "bestMonth": false
    },
    {
      "title":"Legally Blonde",
      "year":2001,
      "imdb":"tt0250494",
      "trailer":"https://www.youtube.com/watch?v=E8I-Qzmbqnc",
      "reviewClip":"https://www.youtube.com/watch?v=E8I-Qzmbqnc",
      "reviewSummary":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dignissim molestie nulla at congue. Cras porttitor tincidunt leo quis sagittis. Duis et dignissim ipsum, a dignissim turpis. Suspendisse dictum justo in dolor blandit hendrerit. Nulla arcu urna, scelerisque a justo et, pretium lobortis arcu. Vestibulum efficitur id risus quis malesuada. Aenean lacinia consectetur massa a ultrices. In orci leo, vehicula non mauris nec, vulputate accumsan magna. Duis at feugiat nibh, vitae eleifend ante,",
      "reviewScore":5,
      "createdAt": new Date(),
      "bestWeek": false,
      "bestMonth": false
    },
    {
      "title":"Pineapple Express",
      "year":2008,
      "imdb":"tt0910936",
      "trailer":"https://www.youtube.com/watch?v=BWZt4v6b1hI",
      "reviewClip":"https://www.youtube.com/watch?v=BWZt4v6b1hI",
      "reviewSummary":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dignissim molestie nulla at congue. Cras porttitor tincidunt leo quis sagittis. Duis et dignissim ipsum, a dignissim turpis. Suspendisse dictum justo in dolor blandit hendrerit. Nulla arcu urna, scelerisque a justo et, pretium lobortis arcu. Vestibulum efficitur id risus quis malesuada. Aenean lacinia consectetur massa a ultrices. In orci leo, vehicula non mauris nec, vulputate accumsan magna. Duis at feugiat nibh, vitae eleifend ante,",
      "reviewScore":8,
      "createdAt": new Date(),
      "bestWeek": false,
      "bestMonth": false
    },
    {
      "title":"Forgetting Sarah Marshall",
      "year":2008,
      "imdb":"tt0848228",
      "trailer":"https://www.youtube.com/watch?v=PyVEHIO6jZ0",
      "reviewClip":"https://www.youtube.com/watch?v=PyVEHIO6jZ0",
      "reviewSummary":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dignissim molestie nulla at congue. Cras porttitor tincidunt leo quis sagittis. Duis et dignissim ipsum, a dignissim turpis. Suspendisse dictum justo in dolor blandit hendrerit. Nulla arcu urna, scelerisque a justo et, pretium lobortis arcu. Vestibulum efficitur id risus quis malesuada. Aenean lacinia consectetur massa a ultrices. In orci leo, vehicula non mauris nec, vulputate accumsan magna. Duis at feugiat nibh, vitae eleifend ante,",
      "reviewScore":8.5,
      "createdAt": new Date(),
      "bestWeek": false,
      "bestMonth": false
    },
    {
      "title":"Friday",
      "year":1995,
      "imdb":"tt0800039",
      "trailer":"https://www.youtube.com/watch?v=umvFBoLOOgo",
      "reviewClip":"https://www.youtube.com/watch?v=umvFBoLOOgo",
      "reviewSummary":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dignissim molestie nulla at congue. Cras porttitor tincidunt leo quis sagittis. Duis et dignissim ipsum, a dignissim turpis. Suspendisse dictum justo in dolor blandit hendrerit. Nulla arcu urna, scelerisque a justo et, pretium lobortis arcu. Vestibulum efficitur id risus quis malesuada. Aenean lacinia consectetur massa a ultrices. In orci leo, vehicula non mauris nec, vulputate accumsan magna. Duis at feugiat nibh, vitae eleifend ante,",
      "reviewScore":9.5,
      "createdAt": new Date(),
      "bestWeek": false,
      "bestMonth": false
    },
    {
      "title":"Black Panther",
      "year":2018,
      "imdb":"tt1825683",
      "trailer":"https://www.youtube.com/watch?v=xjDjIWPwcPU",
      "reviewClip":"https://www.youtube.com/watch?v=xjDjIWPwcPU",
      "reviewSummary":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dignissim molestie nulla at congue. Cras porttitor tincidunt leo quis sagittis. Duis et dignissim ipsum, a dignissim turpis. Suspendisse dictum justo in dolor blandit hendrerit. Nulla arcu urna, scelerisque a justo et, pretium lobortis arcu. Vestibulum efficitur id risus quis malesuada. Aenean lacinia consectetur massa a ultrices. In orci leo, vehicula non mauris nec, vulputate accumsan magna. Duis at feugiat nibh, vitae eleifend ante,",
      "reviewScore":10,
      "createdAt": new Date(),
      "bestWeek": false,
      "bestMonth": true
    },
    {
      "title":"Back to the Future",
      "year":1985,
      "imdb":"tt0088763",
      "trailer":"https://www.youtube.com/watch?v=qvsgGtivCgs",
      "reviewClip":"https://www.youtube.com/watch?v=qvsgGtivCgs",
      "reviewSummary":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dignissim molestie nulla at congue. Cras porttitor tincidunt leo quis sagittis. Duis et dignissim ipsum, a dignissim turpis. Suspendisse dictum justo in dolor blandit hendrerit. Nulla arcu urna, scelerisque a justo et, pretium lobortis arcu. Vestibulum efficitur id risus quis malesuada. Aenean lacinia consectetur massa a ultrices. In orci leo, vehicula non mauris nec, vulputate accumsan magna. Duis at feugiat nibh, vitae eleifend ante,",
      "reviewScore":8.5,
      "createdAt": new Date(),
      "bestWeek": false,
      "bestMonth": false
    },
    {
      "title":"War for the Planet of the Apes",
      "year":2017,
      "imdb":"tt3450958",
      "trailer":"https://www.youtube.com/watch?v=qxjPjPzQ1iU",
      "reviewClip":"https://www.youtube.com/watch?v=qxjPjPzQ1iU",
      "reviewSummary":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dignissim molestie nulla at congue. Cras porttitor tincidunt leo quis sagittis. Duis et dignissim ipsum, a dignissim turpis. Suspendisse dictum justo in dolor blandit hendrerit. Nulla arcu urna, scelerisque a justo et, pretium lobortis arcu. Vestibulum efficitur id risus quis malesuada. Aenean lacinia consectetur massa a ultrices. In orci leo, vehicula non mauris nec, vulputate accumsan magna. Duis at feugiat nibh, vitae eleifend ante,",
      "reviewScore":7,
      "createdAt": new Date(),
      "bestWeek": false,
      "bestMonth": false
    },
    {
      "title":"Star Wars: Episode III - Revenge of the Sith",
      "year":2005,
      "imdb":"tt0121766",
      "trailer":"https://www.youtube.com/watch?v=Yx6F46-_3Ec",
      "reviewClip":"https://www.youtube.com/watch?v=Yx6F46-_3Ec",
      "reviewSummary":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dignissim molestie nulla at congue. Cras porttitor tincidunt leo quis sagittis. Duis et dignissim ipsum, a dignissim turpis. Suspendisse dictum justo in dolor blandit hendrerit. Nulla arcu urna, scelerisque a justo et, pretium lobortis arcu. Vestibulum efficitur id risus quis malesuada. Aenean lacinia consectetur massa a ultrices. In orci leo, vehicula non mauris nec, vulputate accumsan magna. Duis at feugiat nibh, vitae eleifend ante,",
      "reviewScore":9.5,
      "createdAt": new Date(),
      "bestWeek": true,
      "bestMonth": false
    }
  ];
